services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cc_unsa_db
    volumes:
      - cc_unsa_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  cc_unsa_db_data: